[phases.setup]
nixPkgs = ["postgresql", "gcc"]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
PORT = "8000"
